services:
  - type: web
    name: matchvision
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///matchvision.db
